spring:
  application:
    name: auth-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  profiles:
    active: ${SPRING_ACTIVE_PROFILES:test}


secureid:
  jwt:
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL}

  email:
    verification:
      token-ttl: {EMAIL_VERIFICATION_TTL}